// Virtue.exe — Ascension v2.1 (Divine System)
const initialState = {
  settings: { multipliers: { deep:1.0, content:1.2, stream:1.0, gym:0.8, read:0.6, college:0.4 }, targetLevel: 20 },
  levels: (()=>{ let cum=0, arr=[0]; for(let lvl=1; lvl<=100; lvl++){ let xp; if(lvl<=10) xp=150+35*(lvl-1); else if(lvl<=30) xp=500+50*(lvl-11); else xp=1500+75*(lvl-31); cum+=xp; arr.push(cum);} return arr; })(),
  days: {}, achievements: {}, subskills: {}, passives: {}, buffs: [], events: [], quests: { daily: [], weekly: [], lastDaily: null, lastWeekly: null }
};
const ACHIEVES = [["First 10-hour Deep Work Day",100],["7-Day Streak Completed",250],["100 TikToks Posted",500],["First Long-Form Video Published",200],["First 50-Viewer Stream",150],["30 Days No Weed / No Vape",800],["Hit 1,000 Followers",400],["Hit 10,000 Followers",1200],["Workout PR (major)",150],["Spoke on Campus Central Stage",300],["Upload 5 shorts in one day",120],["7 streams in 7 days",220],["First collab stream",150],["1,000 avg daily XP for a week",400],["Bench + Deadlift PR in same week",180],["30-day Daily Log streak",600],["100,000 total XP milestone",800],["Upload 3 long-forms in a month",350]];
const VIRTUE_TREE = { Diligence:["Focus","Persistence","Consistency"], Temperance:["Moderation","Control","Balance"], Patience:["Calm","Endurance","Trust"], Charity:["Compassion","Generosity","Service"], Humility:["Awareness","Openness","Acceptance"], Kindness:["Empathy","Support","Understanding"], Chastity:["Purity","Purpose","Discipline"] };
const PASSIVE_THRESH=[100,250,500,1000];
const PASSIVE_DEFS={Diligence:{Focus:["Deep Work XP +5%","Deep Work XP +10%","Deep Work XP +12%","Deep Work XP +15%"],Persistence:["When streak≥3: +5% XP","+8%","+10%","+12%"],Consistency:["Daily Log +10 XP","+15 XP","+20 XP","+25 XP"]},Temperance:{Moderation:["Gym XP +5%","+8%","+10%","+12%"],Control:["Debuff impact −5%","−8%","−10%","−12%"],Balance:["Aura Density +5%","+8%","+10%","+12%"]},Patience:{Calm:["Mind Resilience +5%","+8%","+10%","+12%"],Endurance:["Reading XP +5%","+8%","+10%","+12%"],Trust:["XP loss on bad days −5%","−8%","−10%","−12%"]},Charity:{Compassion:["Stream XP +5%","+8%","+10%","+12%"],Generosity:["Achievement XP +5%","+8%","+10%","+12%"],Service:["Quest rewards +5%","+8%","+10%","+12%"]},Humility:{Awareness:["College XP +5%","+8%","+10%","+12%"],Openness:["Learning gains +5%","+8%","+10%","+12%"],Acceptance:["Sin penalties −5%","−8%","−10%","−12%"]},Kindness:{Empathy:["Community gains +5%","+8%","+10%","+12%"],Support:["Streak protect (1)","Streak protect (2)","Streak protect (3)","Streak protect (4)"],Understanding:["Balance +5%","+8%","+10%","+12%"]},Chastity:{Purity:["Lust gain −5%","−8%","−10%","−12%"],Purpose:["Flow chance +5%","+8%","+10%","+12%"],Discipline:["All XP +2%","+4%","+6%","+8%"]}};
const QUEST_POOL_DAILY=[{name:"No phone 1h after waking",xp:25},{name:"1 hour Deep Work",xp:30},{name:"Workout complete",xp:25},{name:"15m reading + 5m meditate",xp:20},{name:"Upload 1 TikTok",xp:25},{name:"Evening 3 gratitudes",xp:15},{name:"Stream 30+ minutes",xp:25},{name:"Zero doomscrolling",xp:30}];
const QUEST_POOL_WEEKLY=[{name:"Publish 1 long-form YouTube",xp:150},{name:"3+ streams this week",xp:100},{name:"30+ deep work hours this week",xp:120},{name:"5 gym sessions this week",xp:80},{name:"Zero weed/vape all week",xp:200},{name:"Plan & script next week",xp:60}];
const EVENTS_POOL=[{name:"Grace Period",desc:"Sin penalties nullified for next log",effect:{sinNull:true},hours:6},{name:"Focus Surge",desc:"Deep Work XP +25% next log",effect:{deepBoost:0.25},hours:6},{name:"Virtue Dream",desc:"Aura Density gains doubled today",effect:{auraBoost:1.0},hours:8},{name:"Apathy Breeze",desc:"XP −10% for 3 hours",effect:{xpDown:0.10},hours:3},{name:"Clarity Wind",desc:"Reading XP +25% next log",effect:{readBoost:0.25},hours:6}];
function nowISO(){return new Date().toISOString();} function hoursFromNow(h){return new Date(Date.now()+h*3600*1000).toISOString();}
function load(){const raw=localStorage.getItem('virtue_state_v21'); if(!raw){const state=JSON.parse(JSON.stringify(initialState)); ACHIEVES.forEach(a=>state.achievements[a[0]]={name:a[0],xp:a[1],done:false,date:null}); for(const v in VIRTUE_TREE){state.subskills[v]={}; VIRTUE_TREE[v].forEach(s=>state.subskills[v][s]=0);} generateDaily(state); generateWeekly(state); save(state); return state;} const st=JSON.parse(raw); if(!st.subskills){st.subskills={}; for(const v in VIRTUE_TREE){st.subskills[v]={}; VIRTUE_TREE[v].forEach(s=>st.subskills[v][s]=0);}} if(!st.passives) st.passives={}; if(!st.buffs) st.buffs=[]; if(!st.events) st.events=[]; if(!st.quests){st.quests={daily:[],weekly:[],lastDaily:null,lastWeekly:null}; generateDaily(st); generateWeekly(st);} if(!st.achievements){st.achievements={}; ACHIEVES.forEach(a=> st.achievements[a[0]]={name:a[0],xp:a[1],done:false,date:null});} save(st); return st;}
function save(s){localStorage.setItem('virtue_state_v21', JSON.stringify(s));}
let state = load();
const $ = s=>document.querySelector(s), $$ = s=>Array.from(document.querySelectorAll(s));
function rankTitle(lvl){if(lvl>=80)return'ARCHITECT OF LIGHT'; if(lvl>=60)return'VIRTUOUS ASCENDANT'; if(lvl>=40)return'MASTER'; if(lvl>=30)return'ADEPT'; if(lvl>=20)return'DISCIPLE'; if(lvl>=10)return'APPRENTICE'; return'INITIATE';}
function computeAuraDensity(){let totalH=0,flowH=0; for(let i=0;i<7;i++){const d=new Date(); d.setDate(d.getDate()-i); const k=d.toISOString().slice(0,10); const rec=state.days[k]; if(rec){const h=(rec.deep||0)+(rec.content||0)+(rec.stream||0)+(rec.gym||0)+(rec.read||0)+(rec.college||0); totalH+=h; if(rec.buff==='Y') flowH+=h;}} if(totalH<=0)return 0; return Math.round((flowH/totalH)*100);}
function renderAura(){const val=computeAuraDensity(); const gauge=$('#auraGauge'), txt=$('#auraVal'); const deg=Math.round(360*val/100); gauge.style.background='conic-gradient(var(--gold) '+deg+'deg, #172033 '+deg+'deg)'; txt.textContent=val+'%';}
function activeEffects(){const out={}; const now=new Date().toISOString(); state.buffs=state.buffs.filter(b=>b.expiresAt>now); state.events=state.events.filter(ev=>ev.expiresAt>now); state.events.forEach(ev=>Object.assign(out,ev.effect||{})); return out;}
function questRewardBonus(){let bonus=0; const p=state.passives["Charity.Service"]||0; if(p>=1) bonus+=0.05; if(p>=2) bonus+=0.08; if(p>=3) bonus+=0.10; if(p>=4) bonus+=0.12; return 15*(1+bonus);}
function dayXP(d){const m=state.settings.multipliers; let base=(d.deep||0)*m.deep+(d.content||0)*m.content+(d.stream||0)*m.stream+(d.gym||0)*m.gym+(d.read||0)*m.read+(d.college||0)*m.college; const active=activeEffects(); if(active.xpDown) base*=(1-active.xpDown); const buff=d.buff==='Y'?1.1:1.0, debuff=d.debuff==='Y'?0.75:1.0; const quest=(d.quests||0)*questRewardBonus(); if(active.deepBoost&&(d.deep||0)>0) base+=(d.deep||0)*m.deep*active.deepBoost; if(active.readBoost&&(d.read||0)>0) base+=(d.read||0)*m.read*active.readBoost; return Math.round(base*10*buff*debuff+quest);}
function totalXP(){let sum=0; Object.values(state.days).forEach(d=>sum+=dayXP(d)); Object.values(state.achievements).forEach(a=>{if(a.done) sum+=a.xp;}); return sum;}
function currentLevel(xp){const lvls=state.levels; let lvl=1; for(let i=1;i<lvls.length;i++){ if(xp>=lvls[i]) lvl=i; else break;} return lvl;}
function xpToNext(xp){const lvl=currentLevel(xp); const next=state.levels[Math.min(lvl+1,100)]; return Math.max(0,next-xp);}
function weekHours(){const days=[...Array(7).keys()].map(i=>{const d=new Date(); d.setDate(d.getDate()-i); return d.toISOString().slice(0,10);}); let sum=0; days.forEach(k=>{const d=state.days[k]; if(d) sum+=(d.deep||0)+(d.content||0)+(d.stream||0)+(d.gym||0)+(d.read||0)+(d.college||0);}); return Math.round(sum*100)/100;}
function bestDay(){let max=0; Object.values(state.days).forEach(d=>max=Math.max(max,dayXP(d))); return max;}
function streak(){let s=0; for(let i=0;i<365;i++){const d=new Date(); d.setDate(d.getDate()-i); const k=d.toISOString().slice(0,10); const rec=state.days[k]; const xp=rec?dayXP(rec):0; if(xp>0) s++; else break;} return s;}
const SUB_XP={deep:{"Diligence.Focus":6,"Diligence.Persistence":3,"Diligence.Consistency":3},content:{"Diligence.Persistence":2,"Charity.Compassion":2,"Kindness.Understanding":1},stream:{"Charity.Service":3,"Kindness.Empathy":2,"Humility.Openness":1},gym:{"Temperance.Moderation":4,"Chastity.Discipline":2},read:{"Patience.Calm":3,"Humility.Awareness":2},college:{"Diligence.Consistency":3,"Humility.Acceptance":2}};
function addSubXP(key,amount){const [virt,sub]=key.split('.'); state.subskills[virt][sub]+=amount; const val=state.subskills[virt][sub]; let lvl=0; PASSIVE_THRESH.forEach((t,i)=>{if(val>=t) lvl=i+1;}); const pKey=`${virt}.${sub}`; const prev=state.passives[pKey]||0; if(lvl>prev){state.passives[pKey]=lvl; const text=PASSIVE_DEFS[virt][sub][lvl-1]; sysLog(`[PASSIVE UNLOCKED] ${sub} — ${text}`,'good');}}
function generateDaily(st=state){st.quests.daily=sample(QUEST_POOL_DAILY,3).map(q=>({name:q.name,xp:q.xp,done:false})); st.quests.lastDaily=new Date().toISOString().slice(0,10);}
function generateWeekly(st=state){st.quests.weekly=sample(QUEST_POOL_WEEKLY,3).map(q=>({name:q.name,xp:q.xp,done:false})); st.quests.lastWeekly=new Date().toISOString().slice(0,10);}
function sample(arr,n){const pick=[...arr], out=[]; while(n--&&pick.length){const i=Math.floor(Math.random()*pick.length); out.push(pick.splice(i,1)[0]);} return out;}
function maybeTriggerRandomEvent(){ if(Math.random()<0.10){ triggerRandomEvent(); } }
function triggerRandomEvent(){ const ev=sample(EVENTS_POOL,1)[0]; state.events.push({name:ev.name,desc:ev.desc,effect:ev.effect,expiresAt:hoursFromNow(ev.hours)}); save(state); renderEvents(); sysLog(`[SYSTEM EVENT] ${ev.name} — ${ev.desc}`,'warn'); }
function renderEvents(){const list=$('#eventList'); list.innerHTML=''; const now=new Date(); state.events.forEach(ev=>{const left=Math.max(0,Math.round((new Date(ev.expiresAt)-now)/3600000)); const div=document.createElement('div'); div.className='stat'; div.innerHTML=`<span>${ev.name} — ${ev.desc}</span><strong>${left}h</strong>`; list.appendChild(div);}); const buffs=$('#buffList'); buffs.innerHTML=''; state.events.forEach(ev=>{const left=Math.max(0,Math.round((new Date(ev.expiresAt)-now)/3600000)); const tag=document.createElement('div'); tag.className='tag'; tag.textContent=`${ev.name} • ${left}h`; buffs.appendChild(tag);});}
function sysLog(line,cls=''){const box=$('#sysLog'); if(!box) return; const div=document.createElement('div'); div.className='line '+cls; div.textContent=line; box.prepend(div); while(box.childNodes.length>120){ box.removeChild(box.lastChild);} }
function computeBalance(){let virtues=0,sins=0; Object.values(state.subskills).forEach(obj=>Object.values(obj).forEach(v=>virtues+=v)); Object.values(state.days).forEach(d=>{sins+=(d.slips||0)*10; if(d.debuff==='Y') sins+=10;}); return Math.round(virtues - sins);}
function renderTree(){const area=$('#virtueTree'); area.innerHTML=''; for(const v in VIRTUE_TREE){const branch=document.createElement('div'); branch.className='treeBranch'; const header=document.createElement('div'); header.className='treeHeader'; header.innerHTML=`<h4>${v}</h4><span>▼</span>`; const body=document.createElement('div'); body.className='treeBody'; VIRTUE_TREE[v].forEach(sub=>{const val=state.subskills[v][sub]||0; const pct=Math.min(1,val/1000); const row=document.createElement('div'); row.className='subrow'; row.innerHTML=`<div class="label">${sub}</div><div class="track"><div class="fill" style="width:${(pct*100).toFixed(1)}%"></div></div><div class="passives">${PASSIVE_DEFS[v][sub].map((t,i)=>{const active=(val>=PASSIVE_THRESH[i])?'✅':'○'; return active+' '+t;}).join(' • ')}</div>`; body.appendChild(row);}); branch.appendChild(header); branch.appendChild(body); area.appendChild(branch); header.onclick=()=>{body.style.display=(body.style.display==='none'?'block':'none');}; } $('#balanceTip').textContent='Balance Score: '+computeBalance();}
function renderQuests(){const dq=$('#dailyQuests'); dq.innerHTML=''; state.quests.daily.forEach(q=>{const row=document.createElement('div'); row.className='stat'; row.innerHTML=`<span>${q.done?'✅':''} ${q.name}</span><strong>${q.xp} XP</strong>`; row.onclick=()=>{q.done=!q.done; save(state); renderQuests(); sysLog('[QUEST] '+(q.done?'Completed: ':'Unchecked: ')+q.name,'good');}; dq.appendChild(row);}); const wq=$('#weeklyQuests'); wq.innerHTML=''; state.quests.weekly.forEach(q=>{const row=document.createElement('div'); row.className='stat'; row.innerHTML=`<span>${q.done?'✅':''} ${q.name}</span><strong>${q.xp} XP</strong>`; row.onclick=()=>{q.done=!q.done; save(state); renderQuests(); sysLog('[QUEST] '+(q.done?'Completed: ':'Unchecked: ')+q.name,'good');}; wq.appendChild(row);});}
function renderDashboard(){const xp=totalXP(); $('#totalXP').textContent=xp; const lvl=currentLevel(xp); $('#level').textContent=lvl; $('#xpToNext').textContent=xpToNext(xp); const target=state.settings.targetLevel, targetXP=state.levels[target]; $('#xpBar').style.width=(Math.min(1,xp/targetXP)*100).toFixed(1)+'%'; $('#weekHours').textContent=weekHours(); $('#bestDayXP').textContent=bestDay(); $('#streak').textContent=streak(); const avg=sevenDayAvgXP(); $('#paceHint').textContent=avg>=300?'Calm power. Keep going.':'Breathe. Build. Become.'; $('#rankTitle').textContent=rankTitle(lvl); $('#rankHint').textContent='Next: '+rankTitle(lvl+1); renderAura(); renderEvents();}
function renderRecent(){const cont=$('#recentDays'); cont.innerHTML=''; const keys=Object.keys(state.days).sort().reverse().slice(0,14); keys.forEach(k=>{const d=state.days[k]; const xp=dayXP(d); const div=document.createElement('div'); div.className='day'; div.innerHTML=`<strong>${k}</strong> — ${xp} XP — Notes: ${(d.notes||'')}`; cont.appendChild(div);});}
function renderSettings(){const m=state.settings.multipliers, container=$('#multis'); container.innerHTML=''; [['Deep Work','deep'],['Content','content'],['Streaming','stream'],['Gym','gym'],['Read/Meditate','read'],['College','college']].forEach(([label,key])=>{const wrap=document.createElement('label'); wrap.innerHTML=`${label} <input type="number" step="0.1" value="${m[key]}" data-m="${key}">`; container.appendChild(wrap);}); $('#targetLevel').value=state.settings.targetLevel;}
function sevenDayAvgXP(){let sum=0; for(let i=0;i<7;i++){const d=new Date(); d.setDate(d.getDate()-i); const k=d.toISOString().slice(0,10); const rec=state.days[k]; sum += rec?dayXP(rec):0;} return Math.round(sum/7);}
$$('#tabs button').forEach(btn=>{btn.onclick=()=>{$$('#tabs button').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); const tab=btn.dataset.tab; $$('.tab').forEach(sec=>sec.classList.remove('active')); $('#'+tab).classList.add('active'); if(tab==='dashboard') renderDashboard(); if(tab==='settings') renderSettings(); if(tab==='skills') renderTree(); if(tab==='events') renderEvents(); if(tab==='quests') renderQuests(); if(tab==='log'){ $('#dateInput').value=new Date().toISOString().slice(0,10); renderRecent(); } };});
$('#saveDay').onclick=()=>{const xpBefore=totalXP(); const k=$('#dateInput').value||new Date().toISOString().slice(0,10); const rec={deep:+($('#deepWork').value||0),content:+($('#content').value||0),stream:+($('#stream').value||0),gym:+($('#gym').value||0),read:+($('#read').value||0),college:+($('#college').value||0),quests:+($('#questsCount').value||0),resisted:+($('#resisted').value||0),slips:+($('#slips').value||0),buff:$('#buff').value,debuff:$('#debuff').value,notes:($('#notes').value||'').trim()}; state.days[k]=rec; Object.entries(SUB_XP).forEach(([key,map])=>{const hrs=rec[key]||0; if(!hrs) return; for(const path in map){ addSubXP(path,map[path]*hrs); }}); if(rec.resisted) addSubXP("Chastity.Purity",12*rec.resisted); maybeTriggerRandomEvent(); save(state); const xpAfter=totalXP(); const lvlBefore=currentLevel(xpBefore), lvlAfter=currentLevel(xpAfter); if(lvlAfter>lvlBefore) sysLog('[ASCENSION NOTICE] Level Up → '+lvlAfter+' ('+rankTitle(lvlAfter)+')','warn'); sysLog('[SYSTEM LOG] Saved day '+k+' — '+dayXP(rec)+' XP','good'); renderDashboard(); renderRecent(); renderTree(); renderQuests(); alert('Saved.');};
$('#rerollDaily').onclick=()=>{generateDaily(state); save(state); renderQuests(); sysLog('[QUEST] Daily quests rerolled.','warn');};
$('#rerollWeekly').onclick=()=>{generateWeekly(state); save(state); renderQuests(); sysLog('[QUEST] Weekly quests rerolled.','warn');};
$('#triggerEvent').onclick=()=>{triggerRandomEvent();};
$('#saveSettings').onclick=()=>{$$('#multis input').forEach(inp=> state.settings.multipliers[inp.dataset.m]=+inp.value); state.settings.targetLevel=+($('#targetLevel').value||20); save(state); alert('Settings saved.'); renderDashboard();};
$('#exportData').onclick=()=>{const data=localStorage.getItem('virtue_state_v21')||'{}'; const blob=new Blob([data],{type:'application/json'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='virtue_backup_v21.json'; a.click(); URL.revokeObjectURL(url);};
$('#importData').onclick=()=>$('#importFile').click();
$('#importFile').onchange=(e)=>{const file=e.target.files[0]; if(!file) return; const reader=new FileReader(); reader.onload=()=>{localStorage.setItem('virtue_state_v21', reader.result); state=load(); renderDashboard(); renderSettings(); renderTree(); renderEvents(); renderQuests(); renderRecent(); alert('Imported.');}; reader.readAsText(file);};
$('#resetAll').onclick=()=>{ if(confirm('Reset ALL data?')){ localStorage.removeItem('virtue_state_v21'); state=load(); renderDashboard(); renderSettings(); renderTree(); renderEvents(); renderQuests(); renderRecent(); } };
function startBoot(){ setTimeout(()=>{ document.getElementById('bootOverlay').style.display='none'; }, 3000); }
startBoot(); renderDashboard(); renderSettings(); renderTree(); renderEvents(); renderQuests();
